In [1]:
import pandas as pd
import numpy as np

import joblib

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
jobs_df = pd.read_csv(
    "/content/drive/MyDrive/MyDrive/SmartHire/data/processed/jobs_preprocessed.csv"
)

extra_jobs_df = pd.read_csv(
    "/content/drive/MyDrive/MyDrive/SmartHire/data/processed/extra_jobs_preprocessed.csv"
)

In [4]:
jobs_df.head()

,Job_Title,Company,City,Experience_Level,Skills_Required,Education_Required,Clean_Skills
0,Android Developer,Tech Mahindra,Remote,Senior (6-10 yrs),"Kotlin, Java, REST APIs",M.Tech/M.E.,kotlin java rest apis
1,QA Engineer,Dream11,Lucknow,Senior (6-10 yrs),"Selenium, Manual Testing, Postman, API Testing...",B.Tech/B.E.,selenium manual testing postman api testing py...
2,Business Analyst,HAL,Remote,Senior (6-10 yrs),"JIRA, Excel, Power BI",MCA,jira excel power bi
3,Cybersecurity Analyst,Groww,Mumbai,Mid (3-6 yrs),"Penetration Testing, Python, Ethical Hacking, ...",BCA,penetration testing python ethical hacking sie...
4,Python Developer,Oracle,Remote,Junior (1-3 yrs),"Docker, REST APIs, AWS, PostgreSQL",MCA,docker rest apis aws postgresql

In [5]:
extra_jobs_df.head()

,title,description,Clean_Description
0,Help Desk Analyst- Tier II,Diagnose computer errors and triage to determi...,diagnose computer error triage determine urgen...
1,Clinical Research Associate II,Job Responsibilities:. . As a Clinical Res...,job responsibility clinical research associate...
2,ETL Data Engineer with Oracle Data Integrator ...,Role: ETL Data Engineer with Oracle Data ...,role etl data engineer oracle data integrator ...
3,OR COMM/DATA SUPPORT SPEC,Assumes primary responsibility of unit secreta...,assumes primary responsibility unit secretaria...
4,Data Analyst - Intex Developer,Back to job search Data Analyst - Intex Dev...,back job search data analyst intex developer n...

In [6]:
jobs_df["Search_Text"] = (
    jobs_df["Job_Title"].fillna("") + " " +
    jobs_df["Clean_Skills"].fillna("") + " " +
    jobs_df["Education_Required"].fillna("") + " " +
    jobs_df["Experience_Level"].fillna("")
)

In [7]:
job_vectorizer = TfidfVectorizer(
    max_features=10000,
    ngram_range=(1,2),
    min_df=2,
    max_df=0.95
)

job_vectors = job_vectorizer.fit_transform(jobs_df["Search_Text"])

In [8]:
resume_df = pd.read_csv(
    "/content/drive/MyDrive/MyDrive/SmartHire/data/processed/resume_preprocessed.csv"
)

sample_resume = resume_df.loc[100, "Clean_Resume"]

In [9]:
sample_resume = resume_df.loc[1800, "Clean_Resume"]

In [10]:
print(sample_resume)

qa engineering team lead career overview eight year progressive technical experience quality assurance engineering computer software window environment strong practical theoretical knowledge software quality assurance tool technique proven ability develop system test strategy methodology fullscale system integration testing quality reliability functionality computability expertise development ieee compliant testing documentation key contributor software development team supporting release many new product release several major upgrade existing product experience testing large complex clientserver database application multiplatform product delivery experience pc system experienced window graphical product networking andor data acquisition software experienced manual automated testing working project diverse scope able expertise judgment within defined parameter strong knowledge automated manual black box testing including acceptance functional regression stress compatibility integration testing technique bug reporting error handling responsibility include review software requirement functional specification document participation code walktrough assist design development test plan procedure secure position allow exercise skill obtained education prior work experience qualification analytical problem solving stress tolerance communication skill leadership skill ability resolve nonroutine complex business issue anticipate problem develop alternate solution manage execution successfully ability maintain high energy level extended period time ability communicate clearly efficiently verbally writing ability develop maintain close working relationship end user business analyst documentation specialist tester developer senior management experience building leading closeknit team demanding environment ambiguous undefined frequently changing requirement work experience company name march july qa engineering team lead city state imagicasttm first endtoend service give today educated consumer exactly want retail floor rich product information personalization access unlimited inventory internet combined immediate gratification instore purchase primary responsibility quality imagicast product line lead qa team assigned imagicast related quality task established appropriate qa method inspection test documentation verify software quality prior release shipping product also involved diagnosis product failure performance problem reported field qa task applicable product included verifying operation dvd playback system verifying operation peripheral device eg keyboard printer connected embedded system verifying data collection function wireless data network verifying presentation html page internet device performed qa test complex multi threaded system interpreting specification product feature designed appropriate test case applied qa process reveal functional performance problem affecting web page real time embedded system responsibility included verifying data warehousing data mining application used business intelligence ebusiness server side application multichannel business application personalization feature virtual inventory management application typically found click mortar business company name may february quality assurance engineering manager city state senticaxchangetm mobile solution quickly enables alert twoway push pull transaction content delivery wireless device well landline phone sentica xchangetm approach enables user application initiate communication session complete transaction time interact transact onthego subscriber receive immediate confirmation response telephone cell phone wireless application protocol wap device pda palm vii ce device pocket pc pager well build single implementation desired application enable text voice image video data communication device senticaxchangetm system administration management module functionality provides full access customer information touchpoint enterprise customer employee interact customer application provide breadth functionality needed succeed competitive wireless business primarily responsible performing analysis existing job flow coordination update system documentation providing proposal change needed assisting test execution performed analysis test document design different project within senticaxchangetm including adt gui tool application development tool composer api sam system administration management interface utilizing unix oraclesql various network protocol company name november may qa lead customer careservice application city state oracle customer careservice application full business process management provided functionality support scheduling dispatching spare part logistics service billing field service well contract rounding offering customer care functionality provides full access customer information touchpoint enterprise customer care agent employee interact customer application provide breadth functionality needed succeed competitive support field service depot repair business full business process management provided functionality support scheduling dispatching spare part logistics service billing mobile field service well contract rounding offering customer care functionality provides full access customer information touchpoint enterprise customer care agent employee interact customer performed analysis test document designfor oracle customer careservice application including oracle telephony management otm system otm highvolume crossplatform interface engine utilizing unix xc oraclesql various network protocol primarily responsible performing analysis existing job flow coordination update system documentation providing proposal change needed assisting test execution oracle maintenance repair overhaul mro system resource planning module srp performed high mediumlevel analysis maintenance repair overhaul mro system resource planning srp module within oracle application system decentralized running various platform primarily responsible oversight qa testing process deliverable provided detailed recommendation including complete time cost estimation test process including direction management oversight activity involved defining related requirement infrastructure standard training support method procedure also heavily involved strategic planning related corporatewide year certification coordinated enduser system support staff training administered issue management required escalation jeopardy notification resolution provided verbal written status report seniorlevel management regular basis worked closely civil software engineer create easy use understand informational product nt environment provided change risk implementation management held ultimate responsibility deliverable status report final product delivery designed developed qa test plan manual automated test script quality assurance windowsbased application functionality responsibility included coordination application support activity application analysis testing well operating system support maintenance also assisted coordination delivery enduser training company name february november mail software quality engineer ii city state quality assurance manager role responsibility included leading qa team black box white box testing distributed architecture system client server component proactively involved code walk trough design review meeting learn product great understanding software developed able execute testing lowlevel communication protocol backend database system lead developing test plan test case regression suite make sure test plan executed result communicated developed strategy together development qa team improving qualitytestability component usability final product company name september february senior quality assurance analyst city state foster city electronic invoice presentment new enhancement visa epay service provides member financial institution ability offer billers retail customer electronic invoice delivery capability eip system based window nt platform developed using visual basic access database back end system performs data transport via following communication channel m exchange virtual area network van lan compuserve sprintnet responsible developing lowlevel qa test plan qa reference documentation qa finding document pilot project assist development new testing method procedure improving testing efficiency recommended method automating testing using qa partner tool perform acceptance functional gui usability error handling stress regression testing using black box gray box testing technique validate data integrity security presented level data transport verify transmission completeness database compare input output using msdos batch file check file format known set template test data encryption password protection interviewed new applicant qa analyst position project trained new member team first day assigned responsibility team member wrote daily status report included summery activity performed shift project lead presented qa group department meeting qa team lead conference call every hour included report progress testing cycle made sure needed support provided qa team developing team performed manual automated testing application entered openfound drsbugs tracker bug tracking database verified drsbugs closefixed wrote executed test case acceptance boundary performance regression volume stress testing developed performed automated test case using qa partner window nt environment wrote finding document summary document qa team analysis finding suggestion andor concern found testing cycle project company name march september software quality assurance city state daytimer organizer window personal manager advanced feature work daytimer brand name paper different formatpersonal manager advanced feature work daytimer brand name paper different format test clientserver application database application developed nonprofit organization client donators employee event etc database developed m access m visual basic run window test functionality application creating modifying deleting record provide regression acceptance unit integration testing create execute case regression testing designating area testing develop automated test suite utilizing qa partner emphasized testing feature printing envelope label user preference startup screen entered bug lotus note bug tracking database verified bug education training national education center management city state u management minor national education center san francisco california kensington training program city state u testing computer software kensington training program san mateo california technion university b electrical engineering city il b electrical engineering technion university haifa israel certification national education center professional affiliation electronic invoice presentment new enhancement visa epay service provides member financial institution ability offer billers retail customer electronic invoice delivery capability eip system based window nt platform developed using visual basic access database back end system performs data transport via following communication channel m exchange virtual area network van lan compuserve sprintnet responsible developing lowlevel qa test plan qa reference documentation qa finding document pilot project assist development new testing method procedure improving testing efficiency recommended method automating testing using qa partner tool perform acceptance functional gui usability error handling stress regression testing using black box gray box testing technique validate data integrity security presented level data transport verify transmission completeness database compare input output using msdos batch file check file format known set template test data encryption password protection interviewed new applicant qa analyst position project trained new member team first day assigned responsibility team member wrote daily status report included summery activity performed shift project lead presented qa group department meeting qa team lead conference call every hour included report progress testing cycle made sure needed support provided qa team developing team performed manual automated testing application entered openfound drsbugs tracker bug tracking database verified drsbugs closefixed wrote executed test case acceptance boundary performance regression volume stress testing developed performed automated test case using qa partner window nt environment wrote finding document summary document qa team analysis finding suggestion andor concern found testing cycle project skill quality assurance testing access qa case database regression testing visual basic clientserver client integration integration testing integrator lotus note microsoft window m access m visual basic printing software quality assurance window electrical engineering documentation network protocol oracle proposal sql unix qa test test plan test case application analysis application support automated test script basis billing business process management c contract dispatching issue management logistics maintenance maintenance repair planning module process management qa testing scheduling staff training strategic planning system support telephony test script training graphical user interface gui wireless black box usability adt api application development pocket pc system administration system administration telephone voice wap retail retail marketing team lead architecture database system design review engineer quality engineer software quality engineer test plan white box white box testing black box testing data acquisition database db dbase dbase iv excellent verbal written communication skill ftp ieee internet explorer ipx java javascript linux m office netbeui netscape networking new product novell operation problem solving rdbms san software development software testing solution storage area network structured software system integration tcp tcpip virtual machine visual test vm assurance analyst automated testing back end data integrity do encryption exchange file invoice lan m exchange msdos progress security business intelligence collection data collection data mining data warehousing ebusiness embedded system html inspection inventory qa engineering real time real time embedded real time embedded system shipping wireless data

In [11]:
import joblib

resume_vectorizer = joblib.load(
    "/content/drive/MyDrive/MyDrive/SmartHire/models/tfidf_vectorizer.pkl"
)

classifier = joblib.load(
    "/content/drive/MyDrive/MyDrive/SmartHire/models/resume_classifier.pkl"
)

label_encoder = joblib.load(
    "/content/drive/MyDrive/MyDrive/SmartHire/models/label_encoder.pkl"
)

In [12]:
import joblib

resume_model = joblib.load("/content/drive/MyDrive/MyDrive/SmartHire/models/resume_classifier.pkl")

type(resume_model)

xgboost.sklearn.XGBClassifier

In [13]:
resume_vector = resume_vectorizer.transform([sample_resume])

pred = resume_model.predict(resume_vector)

predicted_category = label_encoder.inverse_transform(pred)[0]

print(predicted_category)

ENGINEERING

In [14]:
jobs_df.columns

Index(['Job_Title', 'Company', 'City', 'Experience_Level', 'Skills_Required',
       'Education_Required', 'Clean_Skills', 'Search_Text'],
      dtype='object')

In [15]:
jobs_df.head()

,Job_Title,Company,City,Experience_Level,Skills_Required,Education_Required,Clean_Skills,Search_Text
0,Android Developer,Tech Mahindra,Remote,Senior (6-10 yrs),"Kotlin, Java, REST APIs",M.Tech/M.E.,kotlin java rest apis,Android Developer kotlin java rest apis M.Tech...
1,QA Engineer,Dream11,Lucknow,Senior (6-10 yrs),"Selenium, Manual Testing, Postman, API Testing...",B.Tech/B.E.,selenium manual testing postman api testing py...,QA Engineer selenium manual testing postman ap...
2,Business Analyst,HAL,Remote,Senior (6-10 yrs),"JIRA, Excel, Power BI",MCA,jira excel power bi,Business Analyst jira excel power bi MCA Senio...
3,Cybersecurity Analyst,Groww,Mumbai,Mid (3-6 yrs),"Penetration Testing, Python, Ethical Hacking, ...",BCA,penetration testing python ethical hacking sie...,Cybersecurity Analyst penetration testing pyth...
4,Python Developer,Oracle,Remote,Junior (1-3 yrs),"Docker, REST APIs, AWS, PostgreSQL",MCA,docker rest apis aws postgresql,Python Developer docker rest apis aws postgres...

In [16]:
print(sorted(resume_df["Category"].unique()))
print("Total Resume Categories:", resume_df["Category"].nunique())

['ACCOUNTANT', 'ADVOCATE', 'AGRICULTURE', 'APPAREL', 'ARTS', 'AUTOMOBILE', 'AVIATION', 'BANKING', 'BPO', 'BUSINESS-DEVELOPMENT', 'CHEF', 'CONSTRUCTION', 'CONSULTANT', 'DESIGNER', 'DIGITAL-MEDIA', 'ENGINEERING', 'FINANCE', 'FITNESS', 'HEALTHCARE', 'HR', 'INFORMATION-TECHNOLOGY', 'PUBLIC-RELATIONS', 'SALES', 'TEACHER']
Total Resume Categories: 24

In [17]:
print(sorted(jobs_df["Job_Title"].unique()))
print("Total Unique Job Titles:", jobs_df["Job_Title"].nunique())

['AI Engineer', 'Android Developer', 'Backend Developer', 'Blockchain Developer', 'Business Analyst', 'Cloud Engineer', 'Computer Vision Engineer', 'Cybersecurity Analyst', 'Data Analyst', 'Data Engineer', 'Data Scientist', 'DevOps Engineer', 'Engineering Manager', 'Frontend Developer', 'Full Stack Developer', 'Java Developer', 'MLOps Engineer', 'Machine Learning Engineer', 'NLP Engineer', 'Node.js Developer', 'Power BI Developer', 'Product Manager', 'Python Developer', 'QA Engineer', 'React Developer', 'Research Scientist', 'Software Engineer', 'Technical Lead', 'UI/UX Designer', 'iOS Developer']
Total Unique Job Titles: 30

In [18]:
category_to_jobs = {
    "ENGINEERING": [
        "Software Engineer",
        "Java Developer",
        "Python Developer",
        "Backend Developer",
        "Frontend Developer",
        "Full Stack Developer",
        "QA Engineer",
        "DevOps Engineer",
        "Cloud Engineer",
        "Engineering Manager",
        "Technical Lead",
        "Research Scientist"
    ],

    "INFORMATION-TECHNOLOGY": [
        "AI Engineer",
        "Machine Learning Engineer",
        "Data Scientist",
        "Data Analyst",
        "Data Engineer",
        "MLOps Engineer",
        "NLP Engineer",
        "Computer Vision Engineer",
        "Cybersecurity Analyst",
        "Blockchain Developer",
        "Node.js Developer",
        "React Developer",
        "Android Developer",
        "iOS Developer",
        "Power BI Developer",
        "Product Manager",
        "Business Analyst"
    ]
}

In [19]:
if predicted_category not in category_to_jobs:
    print(f"No jobs available for category: {predicted_category}")

In [20]:
filtered_jobs = jobs_df[
    jobs_df["Job_Title"].isin(category_to_jobs[predicted_category])
].copy()

In [21]:
if predicted_category in category_to_jobs:
    filtered_jobs = jobs_df[
        jobs_df["Job_Title"].isin(category_to_jobs[predicted_category])
    ].copy()

    print("Number of matching jobs:", len(filtered_jobs))
else:
    print("No jobs available for category:", predicted_category)

Number of matching jobs: 2337

In [22]:
filtered_job_vectors = job_vectorizer.transform(
    filtered_jobs["Search_Text"]
)

In [23]:
resume_job_vector = job_vectorizer.transform([sample_resume])

In [24]:
from sklearn.metrics.pairwise import cosine_similarity

similarity_scores = cosine_similarity(
    resume_job_vector,
    filtered_job_vectors
).flatten()

In [25]:
filtered_jobs["Similarity"] = similarity_scores

In [26]:
recommended_jobs = filtered_jobs.sort_values(
    by="Similarity",
    ascending=False
)

In [27]:
recommended_jobs[
    [
        "Job_Title",
        "Company",
        "City",
        "Experience_Level",
        "Education_Required",
        "Similarity"
    ]
].head(10)

,Job_Title,Company,City,Experience_Level,Education_Required,Similarity
3547,QA Engineer,HCL Technologies,Remote,Mid (3-6 yrs),B.Tech/B.E.,0.343937
2459,QA Engineer,PhonePe,Remote,Lead (10+ yrs),B.Tech/B.E.,0.343771
3876,QA Engineer,Lenskart,Delhi,Lead (10+ yrs),B.Tech/B.E.,0.334556
1620,QA Engineer,Capgemini,Hyderabad,Fresher (0-1 yr),B.Tech/B.E.,0.330362
1188,QA Engineer,Chargebee,Remote,Mid (3-6 yrs),B.Tech/B.E.,0.327816
4359,QA Engineer,Flipkart,Hyderabad,Junior (1-3 yrs),B.Tech/B.E.,0.327710
4997,QA Engineer,BHEL,Remote,Mid (3-6 yrs),B.Tech/B.E.,0.327341
977,QA Engineer,Zerodha,Bhubaneswar,Junior (1-3 yrs),M.Tech/M.E.,0.322734
3101,QA Engineer,InMobi,Mumbai,Junior (1-3 yrs),B.Tech/B.E.,0.319767
2806,QA Engineer,Google,Chennai,Mid (3-6 yrs),B.Tech/B.E.,0.317572

In [28]:
from sklearn.metrics.pairwise import cosine_similarity

def recommend_jobs(resume_text, top_n=10):

    # -----------------------------
    # Step 1: Predict Resume Category
    # -----------------------------
    resume_vector = resume_vectorizer.transform([resume_text])

    pred = resume_model.predict(resume_vector)

    predicted_category = label_encoder.inverse_transform(pred)[0]

    print("Predicted Category:", predicted_category)

    # -----------------------------
    # Step 2: Check if category exists
    # -----------------------------
    if predicted_category not in category_to_jobs:

        print("No jobs available for this category.")

        return None

    # -----------------------------
    # Step 3: Filter Jobs
    # -----------------------------
    filtered_jobs = jobs_df[
        jobs_df["Job_Title"].isin(category_to_jobs[predicted_category])
    ].copy()

    # -----------------------------
    # Step 4: Transform Jobs
    # -----------------------------
    filtered_job_vectors = job_vectorizer.transform(
        filtered_jobs["Search_Text"]
    )

    # -----------------------------
    # Step 5: Transform Resume
    # -----------------------------
    resume_job_vector = job_vectorizer.transform([resume_text])

    # -----------------------------
    # Step 6: Cosine Similarity
    # -----------------------------
    similarity = cosine_similarity(
        resume_job_vector,
        filtered_job_vectors
    ).flatten()

    # -----------------------------
    # Step 7: Attach Similarity
    # -----------------------------
    filtered_jobs["Similarity"] = similarity

    filtered_jobs["Match %"] = (
        filtered_jobs["Similarity"] * 100
    ).round(2)

    # -----------------------------
    # Step 8: Sort
    # -----------------------------
    recommended_jobs = filtered_jobs.sort_values(
        by="Similarity",
        ascending=False
    )

    # -----------------------------
    # Step 9: Return Top Jobs
    # -----------------------------
    return recommended_jobs[
        [
            "Job_Title",
            "Company",
            "City",
            "Experience_Level",
            "Education_Required",
            "Match %"
        ]
    ].head(top_n)

In [29]:
recommend_jobs(sample_resume)

Predicted Category: ENGINEERING

,Job_Title,Company,City,Experience_Level,Education_Required,Match %
3547,QA Engineer,HCL Technologies,Remote,Mid (3-6 yrs),B.Tech/B.E.,34.39
2459,QA Engineer,PhonePe,Remote,Lead (10+ yrs),B.Tech/B.E.,34.38
3876,QA Engineer,Lenskart,Delhi,Lead (10+ yrs),B.Tech/B.E.,33.46
1620,QA Engineer,Capgemini,Hyderabad,Fresher (0-1 yr),B.Tech/B.E.,33.04
1188,QA Engineer,Chargebee,Remote,Mid (3-6 yrs),B.Tech/B.E.,32.78
4359,QA Engineer,Flipkart,Hyderabad,Junior (1-3 yrs),B.Tech/B.E.,32.77
4997,QA Engineer,BHEL,Remote,Mid (3-6 yrs),B.Tech/B.E.,32.73
977,QA Engineer,Zerodha,Bhubaneswar,Junior (1-3 yrs),M.Tech/M.E.,32.27
3101,QA Engineer,InMobi,Mumbai,Junior (1-3 yrs),B.Tech/B.E.,31.98
2806,QA Engineer,Google,Chennai,Mid (3-6 yrs),B.Tech/B.E.,31.76

In [30]:
import joblib

joblib.dump(
    job_vectorizer,
    "/content/drive/MyDrive/MyDrive/SmartHire/models/job_vectorizer.pkl"
)

['/content/drive/MyDrive/MyDrive/SmartHire/models/job_vectorizer.pkl']

In [31]:
joblib.dump(
    category_to_jobs,
    "/content/drive/MyDrive/MyDrive/SmartHire/models/category_to_jobs.pkl"
)

['/content/drive/MyDrive/MyDrive/SmartHire/models/category_to_jobs.pkl']

In [32]:
jobs_df.to_csv(
    "/content/drive/MyDrive/MyDrive/SmartHire/data/processed/jobs_recommendation.csv",
    index=False
)